# Find UF persons who are missing the UFEntity property (using their GatorLink)
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
PREFIX  ufVivo: <http://vivo.ufl.edu/ontology/vivo-ufl/>

SELECT  (concat("<", str(?uri), "> ", ?gatorLink) AS ?Person_missing_UFEntity)
WHERE
  { ?uri a foaf:Person .
    ?uri ufVivo:gatorlink ?gatorLink
    FILTER NOT EXISTS {?uri a ufVivo:UFEntity }
  }
ORDER BY ?gatorLink
